blog/urls.py
from django.urls import path
#from . import views

from django.conf import settings
from django.conf.urls.static import static
from .forms import NewsForm, AuthorizationForm
from .views import NewsContent, Gallery, AddNews, About, Authorization, ImageUpdateView, ImageCreateView, ImageDeleteView, ImageGroupCreateView



urlpatterns = [
    path('', NewsContent.as_view(), name="Главная"),
    path('gallery/', Gallery.as_view(), name="Галерея"),
    path('add_news/', AddNews.as_view(), name="add_news"),
    path('about/', About.as_view(), name="О нас"),
    path('authorization/', Authorization.as_view(), name="authorization"),
    path('image/<int:pk>/edit/', ImageUpdateView.as_view(), name='image_edit'),
    path('image/add/', ImageCreateView.as_view(), name='image_add'),
    path('image/<int:pk>/delete/', ImageDeleteView.as_view(), name='image_delete'),
    path('imagegroup_add/', ImageGroupCreateView.as_view(), name='imagegroup_add'),
    #path('nav/', views.nav, name="nav_menu"),
    
]

zastava/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from blog import views
from curses import views




urlpatterns = [
    path('bg/pfa/', admin.site.urls),
    path('', include('blog.urls')),
    path('curses/', include('curses.urls')),
    path('users/', include('users.urls', namespace="users")),
    path('survey/', include('survey.urls', namespace="survey")),
]

if settings.DEBUG:
     import debug_toolbar
     urlpatterns = [
          path('__debug__/', include(debug_toolbar.urls)),
     ] + urlpatterns

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class News(models.Model):
    id = models.AutoField(primary_key=True, db_column='news_ID')
    title = models.CharField(max_length=100)
    content = models.TextField()
    autor = models.ForeignKey('users.User', on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    

    class Meta:
        db_table = 'News'
        verbose_name = 'новость'
        verbose_name_plural = 'новости'

    def __str__(self):
        return self.title



class ImageGroup(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Image(models.Model):
    group = models.ForeignKey(ImageGroup, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')
    description = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.description

blog/forms.py
from django import forms
from .models import News, ImageGroup, Image




class NewsForm(forms.ModelForm):

    title = forms.CharField(label='Заголовок', max_length=255, widget = forms.TextInput(attrs={'class':'form-control'}))
    content = forms.CharField(label='Текст', widget = forms.Textarea(attrs={'class':'form-control'}))
    class Meta:
        model = News
        fields = [ 'title', 'content']

#Добавим форму для создания группы галерий и загрузки фотокартинок 

# class editImageForm(forms.ModelForm):
#     class Meta:
#         model = Image
#         fields = ['group', 'image', 'description']
#         widgets = {
#             'image': forms.ClearableFileInput(attrs={'multiple': True}),
#         }

class editImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['group', 'image', 'description']
        widgets = {
            'group': forms.Select(attrs={'class': 'form-control'}),
            'image': forms.ClearableFileInput(attrs={
                'multiple': True,
                'class': 'form-control'
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 3
            })
        }


class ImageGroupForm(forms.ModelForm):
    
    class Meta:
        model = ImageGroup
        fields = ['name']
        labels = {
            'name': 'Название',
        }

        


class AuthorizationForm(forms.Form):
    username = forms.CharField(label='Логин', max_length=255)
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)

blog/views.py
from .models import News
from .models import ImageGroup, Image
from .forms import NewsForm, AuthorizationForm, editImageForm, ImageGroupForm
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, reverse
from django.template.context_processors import request
from django.views.decorators.cache import cache_page
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import View, TemplateView, FormView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
import os




nav_menu = {
    'menu': ['Главная', 'Галерея', 'О нас', 'Курсы'],
}

class MenuMixin(View):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = nav_menu['menu']
        return context

class NewsContent(MenuMixin, TemplateView):
    template_name = 'blog/news.html'
    extra_context = {'title': 'Новости'}
    list_per_page = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        sort = self.request.GET.get('sort', 'date')
        order = self.request.GET.get('order', 'asc')

        valid_sort_fields = {'date', 'views', 'adds'}
        if sort not in valid_sort_fields:
            sort = 'date'

        if order == 'desc':
            order_by = sort
        else:
            order_by = f'-{sort}'

        news = News.objects.all().order_by(order_by)

        # Пагинация
        paginator = Paginator(news, self.list_per_page)
        page = self.request.GET.get('page')

        try:
            news_page = paginator.page(page)
        except PageNotAnInteger:
            news_page = paginator.page(1)
        except EmptyPage:
            news_page = paginator.page(paginator.num_pages)

        context['news'] = news_page
        return context

class Gallery(MenuMixin, TemplateView):
    template_name = 'blog/gallery.html'
    extra_context = {'title': 'Галерея'}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['groups'] = ImageGroup.objects.all()
        context['menu'] = nav_menu['menu']
        return context

class ImageGroupCreateView(MenuMixin, UserPassesTestMixin, CreateView):
    model = ImageGroup
    form_class = ImageGroupForm
    template_name = 'blog/imagegroup_form.html'
    success_url = reverse_lazy('Галерея')

    def test_func(self):
        
        return self.request.user.is_superuser or self.request.user.groups.filter(name='moderator').exists()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['active_tab'] = 'imagegroup_add'  
        return context
class ImageUpdateView(UserPassesTestMixin, UpdateView):
    model = Image
    form_class = editImageForm
    template_name = 'blog/edit_image_form.html'
    success_url = reverse_lazy('Галерея')  
    def test_func(self):
        
        return self.request.user.is_superuser or self.request.user.groups.filter(name='moderator').exists()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = nav_menu['menu']
        return context
class ImageCreateView(UserPassesTestMixin, CreateView):
    model = Image
    form_class = editImageForm
    template_name = 'blog/edit_image_form.html'
    success_url = reverse_lazy('Галерея')  

    def test_func(self):
        
        return self.request.user.is_superuser or self.request.user.groups.filter(name='moderator').exists()
    def get_initial(self):
        initial = super().get_initial()
        group_id = self.request.GET.get('group')
        if group_id:
            initial['group'] = group_id
        return initial

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = nav_menu['menu']
        return context

    def form_valid(self, form):
        images = self.request.FILES.getlist('image')
        if images:
            for image in images:
                Image.objects.create(
                    group=form.cleaned_data['group'],
                    image=image,
                    description=form.cleaned_data['description']
                )
        return redirect(self.success_url)
class ImageDeleteView(UserPassesTestMixin, DeleteView):
    model = Image
    template_name = 'blog/image_confirm_delete.html'
    success_url = reverse_lazy('Галерея')  
    def test_func(self):
        
        return self.request.user.is_superuser or self.request.user.groups.filter(name='moderator').exists()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = nav_menu['menu']
        context['image'] = self.get_object().image
        return context

    def form_valid(self, form):
        self.object = self.get_object()
        if self.object.image:  
            if os.path.isfile(self.object.image.path):
                os.remove(self.object.image.path)
        
        self.object.delete()
        return HttpResponseRedirect(self.get_success_url())
class AddNews(LoginRequiredMixin, PermissionRequiredMixin, MenuMixin, FormView, UserPassesTestMixin):
    template_name = 'blog/add_news.html'
    extra_context = {'title': 'Добавить новость'}
    form_class = NewsForm
    login_url = reverse_lazy('users:login')
    redirect_field_name = 'next'
    permission_required = 'blog.add_news'
    
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.groups.filter(name='Moderator').exists()

    def form_valid(self, form):
        news = form.save(commit=False)
        news.autor = self.request.user
        news.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('users:profile', kwargs={'pk': self.request.user.pk})
   

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['active_tab'] = 'add_news'  # Добавляем переменную active_tab в контекст
        return context


class About(MenuMixin, TemplateView):
    template_name = 'blog/about.html'
    extra_context = {'title': 'О нас'}



class Authorization(MenuMixin, FormView):
    template_name = 'blog/authorization.html'
    extra_context = {'title': 'Авторизация'}
    form_class = AuthorizationForm
    success_url = '/'

    def form_valid(self, form):
        return super().form_valid(form)

blog/templates/blog/about.html
{% extends "base.html" %} 
{% block content %}

<p>Организация МНОО "ЗАСТАВА-86", находящаяся по адресу Ханты-Мансийский Автономный округ - Югра, г Нижневартовск, ул Маршала Жукова, д 8А, кв 68, была зарегистрирована 29-10-2014 с присвоением ИНН 8603998369 и ОГРН 1148600001252. Руководителем организации является Левченко Александр Николаевич. </p>
<p>Основным видом деятельности организации является Деятельность прочих общественных организаций, не включенных в другие группировки. Текущий статус организации действующая.</p>

{% endblock %}

blog/templates/blog/add_news.html
{% extends "users/base_profile.html" %}

{% load static %}



{% block content_profile %}

    <div class="container">
        <h1>Добавить новость</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn_custom">Добавить</button>
        </form>
    </div>


{% endblock %}
    

blog/templates/blog/authorization.html
{% extends "base.html" %}
{% block content %}

    <h1>Войти</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Войти</button>
    </form>


{% endblock %}

blog/templates/blog/edit_image_form.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <h2>Изменить изображение</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
</div>

{% endblock %}

blog/templates/blog/gallery.html
{% extends "base.html" %}

{% block content %}
<style>
    .Btn {
        display: flex;
        justify-content: space-around;
    }
    .prevBtn {
        width: 50%;
        border: none;
        margin-right: 1px;
    }
    .nextBtn {
        width: 50%;
        border: none;
        margin-left: 1px;
    }
    .image-actions {
        display: flex;
        justify-content: space-between;
        margin-top: 10px;
    }
    .modal {
        display: none;
        position: fixed;
        z-index: 1;
        padding-top: 60px;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgb(0,0,0);
        background-color: rgba(0,0,0,0.9);
    }
    .modal-content {
        margin: auto;
        display: block;
        width: 80%;
        max-width: 700px;
    }
    .close {
        position: absolute;
        top: 15px;
        right: 35px;
        color: #f1f1f1;
        font-size: 40px;
        font-weight: bold;
        transition: 0.3s;
    }
    .close:hover,
    .close:focus {
        color: #bbb;
        text-decoration: none;
        cursor: pointer;
    }
</style>
<div class="slider-container">
    {% for group in groups %}
        <div class="sliders" data-group-id="{{ group.pk }}">
            <h2>{{ group.name }}</h2>
            <div class="slider">
                <div class="slidery">
                    {% for image in group.image_set.all %}
                        <img src="{{ image.image.url }}" alt="{{ image.description }}" class="slide" data-image-id="{{ image.pk }}" style="display: none;" onclick="openModal(this)">
                    {% endfor %}
                </div>
                <div class="Btn">
                    <button class="prevBtn" onclick="prevImage(this)">Назад</button>
                    <button class="nextBtn" onclick="nextImage(this)">Следующий</button>
                </div>
                {% if user.is_staff or user.is_superuser %}
                    <div class="image-actions">
                        <a href="{% url 'image_add' %}?group={{ group.pk }}">Добавить изображение</a>
                        <a href="#" class="edit-link">Изменить</a>
                        <a href="#" class="delete-link">Удалить</a>
                    </div>
                {% endif %}
            </div>
        </div>
    {% endfor %}
</div>

<!-- The Modal -->
<div id="myModal" class="modal">
    <span class="close">&times;</span>
    <img class="modal-content" id="modalImg">
</div>

<script>
    function updateLinks(groupId, imageId) {
        const slider = document.querySelector(`.sliders[data-group-id="${groupId}"]`);
        const editLink = slider.querySelector('.edit-link');
        const deleteLink = slider.querySelector('.delete-link');
        if (editLink && deleteLink) {
            editLink.href = `{% url 'image_edit' 0 %}`.replace('0', imageId);
            deleteLink.href = `{% url 'image_delete' 0 %}`.replace('0', imageId);
            console.log(`Updated links for group ${groupId} and image ${imageId}`);
            console.log(`Edit link: ${editLink.href}`);
            console.log(`Delete link: ${deleteLink.href}`);
        } else {
            console.error(`Links not found for group ${groupId}`);
        }
    }

    function prevImage(button) {
        const slider = button.closest('.sliders');
        const images = slider.querySelectorAll('.slide');
        let currentIndex = Array.from(images).findIndex(img => img.style.display !== 'none');
        currentIndex = (currentIndex - 1 + images.length) % images.length;
        images.forEach((img, index) => {
            img.style.display = index === currentIndex ? 'block' : 'none';
        });
        const groupId = slider.dataset.groupId;
        const imageId = images[currentIndex].dataset.imageId;
        console.log(`Prev image: groupId=${groupId}, imageId=${imageId}`);
        updateLinks(groupId, imageId);
    }

    function nextImage(button) {
        const slider = button.closest('.sliders');
        const images = slider.querySelectorAll('.slide');
        let currentIndex = Array.from(images).findIndex(img => img.style.display !== 'none');
        currentIndex = (currentIndex + 1) % images.length;
        images.forEach((img, index) => {
            img.style.display = index === currentIndex ? 'block' : 'none';
        });
        const groupId = slider.dataset.groupId;
        const imageId = images[currentIndex].dataset.imageId;
        console.log(`Next image: groupId=${groupId}, imageId=${imageId}`);
        updateLinks(groupId, imageId);
    }

    // Initialize the first image and links
    document.addEventListener('DOMContentLoaded', () => {
        const sliders = document.querySelectorAll('.sliders');
        sliders.forEach(slider => {
            const images = slider.querySelectorAll('.slide');
            const groupId = slider.dataset.groupId;
            if (images.length > 0) {
                images[0].style.display = 'block';
                const imageId = images[0].dataset.imageId;
                console.log(`Initial image: groupId=${groupId}, imageId=${imageId}`);
                updateLinks(groupId, imageId);
            }
        });
    });

    // Get the modal
    var modal = document.getElementById("myModal");

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // When the user clicks on <span> (x), close the modal
    span.onclick = function() {
        modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }

    function openModal(img) {
        var modalImg = document.getElementById("modalImg");
        modal.style.display = "block";
        modalImg.src = img.src;
    }
</script>
{% endblock %}










{% comment %} {% extends "base.html" %}

{% block content %}
<style>
    .Btn {
        display: flex;
        justify-content: space-around;
    }
    .prevBtn {
        width: 50%;
        border: none;
        margin-right: 1px;
    }
    .nextBtn {
        width: 50%;
        border: none;
        margin-left: 1px;
    }
    .image-actions {
        display: flex;
        justify-content: space-between;
        margin-top: 10px;
    }
</style>
<div class="slider-container">
    {% for group in groups %}
        <div class="sliders" data-group-id="{{ group.pk }}">
            <h2>{{ group.name }}</h2>
            <div class="slider">
                <div class="slidery">
                    {% for image in group.image_set.all %}
                        <img src="{{ image.image.url }}" alt="{{ image.description }}" class="slide" data-image-id="{{ image.pk }}" style="display: none;">
                    {% endfor %}
                </div>
                <div class="Btn">
                    <button class="prevBtn" onclick="prevImage(this)">Назад</button>
                    <button class="nextBtn" onclick="nextImage(this)">Следующий</button>
                </div>
                {% if user.is_staff or user.is_superuser %}
                    <div class="image-actions">
                        <a href="{% url 'image_add' %}?group={{ group.pk }}">Добавить изображение</a>
                        <a href="#" class="edit-link">Изменить</a>
                        <a href="#" class="delete-link">Удалить</a>
                    </div>
                {% endif %}
            </div>
        </div>
    {% endfor %}
</div>

<script>
    function updateLinks(groupId, imageId) {
        const slider = document.querySelector(`.sliders[data-group-id="${groupId}"]`);
        const editLink = slider.querySelector('.edit-link');
        const deleteLink = slider.querySelector('.delete-link');
        if (editLink && deleteLink) {
            editLink.href = `{% url 'image_edit' 0 %}`.replace('0', imageId);
            deleteLink.href = `{% url 'image_delete' 0 %}`.replace('0', imageId);
            console.log(`Updated links for group ${groupId} and image ${imageId}`);
            console.log(`Edit link: ${editLink.href}`);
            console.log(`Delete link: ${deleteLink.href}`);
        } else {
            console.error(`Links not found for group ${groupId}`);
        }
    }

    function prevImage(button) {
        const slider = button.closest('.sliders');
        const images = slider.querySelectorAll('.slide');
        let currentIndex = Array.from(images).findIndex(img => img.style.display !== 'none');
        currentIndex = (currentIndex - 1 + images.length) % images.length;
        images.forEach((img, index) => {
            img.style.display = index === currentIndex ? 'block' : 'none';
        });
        const groupId = slider.dataset.groupId;
        const imageId = images[currentIndex].dataset.imageId;
        console.log(`Prev image: groupId=${groupId}, imageId=${imageId}`);
        updateLinks(groupId, imageId);
    }

    function nextImage(button) {
        const slider = button.closest('.sliders');
        const images = slider.querySelectorAll('.slide');
        let currentIndex = Array.from(images).findIndex(img => img.style.display !== 'none');
        currentIndex = (currentIndex + 1) % images.length;
        images.forEach((img, index) => {
            img.style.display = index === currentIndex ? 'block' : 'none';
        });
        const groupId = slider.dataset.groupId;
        const imageId = images[currentIndex].dataset.imageId;
        console.log(`Next image: groupId=${groupId}, imageId=${imageId}`);
        updateLinks(groupId, imageId);
    }

    // Initialize the first image and links
    document.addEventListener('DOMContentLoaded', () => {
        const sliders = document.querySelectorAll('.sliders');
        sliders.forEach(slider => {
            const images = slider.querySelectorAll('.slide');
            const groupId = slider.dataset.groupId;
            if (images.length > 0) {
                images[0].style.display = 'block';
                const imageId = images[0].dataset.imageId;
                console.log(`Initial image: groupId=${groupId}, imageId=${imageId}`);
                updateLinks(groupId, imageId);
            }
        });
    });
</script>
{% endblock %}
    {% endcomment %}

blog/templates/blog/image_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <h2>Подтвердите удаление изображения</h2>
        <form method="post">
            {% csrf_token %}
            <p>Вы уверены, что хотите удалить это изображение?</p>
            <img src="{{ image.url }}" alt="Изображение для удаления" style="max-width: 100%;">
            <button type="submit">Удалить</button>
            <a href="{% url 'Галерея' %}">Отмена</a>
        </form>
    </div>
{% endblock %}

blog/templates/blog/imagegroup_form.html
{% extends "users/base_profile.html" %}

{% load static %}



{% block content_profile %}
    <h2>Добавить новое название группы изображений</h2>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
    </form>

{% endblock %}

blog/templates/blog/news.html
{% extends "base.html" %}
{% block content %}
    {% for item in news %}
        <div class="content">
            <div class="content_block">
                <div class="news">
                    <div class="news_block">
                        <div class="time_news">Опубликованно: {{ item.date }}</div>
                        <div class="text_news">
                            {{ item.content }}
                            <p>Автор: {{ item.autor }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

    <div class="pagination justify-content-center">
        <span class="step-links">
            {% if news.has_previous %}
                <a class="btn " href="?page=1">&laquo; первая</a>
                <a class="btn " href="?page={{ news.previous_page_number }}">предыдущая</a>
            {% endif %}
    
            <span class="current badge bg-secondary">
                Страница {{ news.number }} из {{ news.paginator.num_pages }}.
            </span>
    
            {% if news.has_next %}
                <a class="btn " href="?page={{ news.next_page_number }}">следующая</a>
                <a class="btn " href="?page={{ news.paginator.num_pages }}">последняя &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}