blog/urls.py
from django.urls import path
#from . import views

from django.conf import settings
from django.conf.urls.static import static
from .forms import NewsForm, AuthorizationForm
from .views import NewsContent, Gallery, AddNews, About, Authorization, ImageUpdateView, ImageCreateView, ImageDeleteView, ImageGroupCreateView



urlpatterns = [
    path('', NewsContent.as_view(), name="Главная"),
    path('gallery/', Gallery.as_view(), name="Галерея"),
    path('add_news/', AddNews.as_view(), name="add_news"),
    path('about/', About.as_view(), name="О нас"),
    path('authorization/', Authorization.as_view(), name="authorization"),
    path('image/<int:pk>/edit/', ImageUpdateView.as_view(), name='image_edit'),
    path('image/add/', ImageCreateView.as_view(), name='image_add'),
    path('image/<int:pk>/delete/', ImageDeleteView.as_view(), name='image_delete'),
    path('imagegroup_add/', ImageGroupCreateView.as_view(), name='imagegroup_add'),
    #path('nav/', views.nav, name="nav_menu"),
    
]

survey/urls.py
from django.urls import path
from . import views

from .views import (
    GroupSelectionView,
    StartSurveyView,
    QuestionView,
    ResultsView,
    AddQuestionView,
    AllResultsView,
)
app_name = 'survey'

urlpatterns = [
    path('group_selection/', GroupSelectionView.as_view(), name='group_selection'),
    path('start/', StartSurveyView.as_view(), name='start_survey'),
    path('question/<int:question_id>/', QuestionView.as_view(), name='question'),
    path('results/', ResultsView.as_view(), name='results'),
    path('all_results/', AllResultsView.as_view(), name='all_results'),
    path('add_question/', AddQuestionView.as_view(), name='add_question'),
]

users/urls.py
from django.urls import path
from . import views
from .views import (LoginUserView,
                    LogoutUsersView,
                    RegistrationView,
                    ProfileUser,
                    UserPasswordChange,
                    UserPasswordChangeDone
                    )

app_name = "users"

urlpatterns = [
    path('login/', LoginUserView.as_view(), name="login"),
    path('logout/', LogoutUsersView.as_view(), name="logout"),
    path('signup/', views.RegistrationView.as_view(), name="signup"),
    path('profile/<int:pk>/', ProfileUser.as_view(), name='profile'),
    path('password_change/', UserPasswordChange.as_view(), name="password_change"),
    path('password_change_done/', UserPasswordChangeDone.as_view(), name='password_change_done'),

]

zastava/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from blog import views
from curses import views




urlpatterns = [
    path('bg/pfa/', admin.site.urls),
    path('', include('blog.urls')),
    path('curses/', include('curses.urls')),
    path('users/', include('users.urls', namespace="users")),
    path('survey/', include('survey.urls', namespace="survey")),
]

if settings.DEBUG:
     import debug_toolbar
     urlpatterns = [
          path('__debug__/', include(debug_toolbar.urls)),
     ] + urlpatterns

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=zastava-86, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="{% static "blog\css\style.css" %}" rel="stylesheet">
    
    <title>{{ title }}</title>
  </head>
  <body>
    <main>
      <div class="zas">
        <div class="heider">
          <div class="logo">
            <img src="{% static 'blog\img\logo.png' %}" alt="photo" />
          </div>
          <div class="text_title">
            <p>РОО "Застава-86"</p>
          </div>
        </div>
        <div class="main">{% include "include/nav.html" %}</div>
        <div class="z-1">
          <ul class="navbar-nav"> <!-- Элементы правой части без выравнивания по левому краю -->
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:profile' pk=user.pk %}">Вы вошли как, <strong> {{user.first_name}} </strong>  /</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Для просмотра раздела <strong>"Курсы"</strong>, Вам необходимо <strong>Войти</strong></a>
              </li>
              {% comment %} <li class="nav-item">
                <a class="nav-link" href="{% url 'users:signup' %}">Регистрация</a>
              </li> {% endcomment %}
              {% endif %}
            </ul>
      </div>
        
        {% block content %} {% endblock %}
        <div class="footer">{% include "include/nav.html" %}</div>
      </div>
    </main>

    <script src="{% static 'blog/script.js' %}"></script>
    <script src="{% static 'blog/js/lazyload.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

templates/curses.html
{% extends "base.html" %}
{% block content %}

    
        {% if show_survey %}
        <div class="cards">
            <ul>
                <a href="{% url 'survey:group_selection' %}">
                    <li>
                        <h2>Тестирование</h2>
                        <img src="" alt="">
                    </li>
                </a>
            </ul>
        </div>
        {% endif %}
        <div class="cards">
            <ul>
                {% for card in cards %}
                <a href="{% url 'card_list' category_id=card.category.id %}">
                    <li>
                        <h2>{{ card.title }}</h2>
                        <img src="{{ card.image.url }}" alt="{{ card.title }}">
                    </li>
                </a>
                {% endfor %}
            </ul>
        </div>

    
    {% block curses %}
    {% endblock %}

{% endblock content %}